from playwright.sync_api import Page


def test_login(page: Page):
    page.goto('https://the-internet.herokuapp.com/')
    form_auth_link = page.get_by_role('link', name='Form Authentication')
    form_auth_link.click()
    login_field = page.get_by_role('textbox', name='username')
    login_field.fill('asdasd')
    password_field = page.get_by_role('textbox', name='password')
    password_field.fill('Qwerty@123')
    login_button = page.get_by_role('button')
    login_button.click()


def test_student_form(page: Page):
    page.goto('https://demoqa.com/automation-practice-form')
    firstname = page.get_by_placeholder('First Name')
    firstname.fill('Kot')
    lastname = page.get_by_placeholder('Last Name')
    lastname.fill('Chorny')
    email = page.get_by_placeholder('name@example.com')
    email.fill('kot_chorny@somemail.com')
    gender = page.locator('//*[@value="Male"]/following::label[@for="gender-radio-1"]')
    gender.click()
    mobile = page.get_by_placeholder('Mobile Number')
    mobile.fill('1234567890')
    date_of_birth = page.locator('//*[@id="dateOfBirthInput"]')
    date_of_birth.click()
    for _ in range(10):
        date_of_birth.press('Backspace')
    date_of_birth.fill(' June 2020')
    subjects = page.locator('//*[@id="subjectsInput"]')
    subjects.click()
    subjects.fill('c')
    chemistry = page.get_by_text('Chemistry')
    chemistry.click()
    address = page.locator('//*[@id = "currentAddress"]')
    address.fill('345 Baker street')
    hobby = page.locator('//*[@for="hobbies-checkbox-1"]')
    hobby.click()
    state = page.get_by_text('Select State')
    state.click()
    state.press("ArrowDown")
    state.press("Enter")
    city = page.get_by_text('Select City')
    city.click()
    city.press("Enter")
    submit_button = page.get_by_role('button')
    submit_button.click()
